//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedTaskUser
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CompletedTaskID { get; set; }
    
        public virtual TaskNames TaskNames { get; set; }
        public virtual Users Users { get; set; }
    }
}
