//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime DateOfOrder { get; set; }
        public int OrderStatusID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Service Service { get; set; }
    }
}
