//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksIBanks
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public int BankID { get; set; }
        public int Variant { get; set; }
        public string VarDescription { get; set; }
    
        public virtual TaskBanks TaskBanks { get; set; }
        public virtual TaskNames TaskNames { get; set; }
    }
}
