//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskNames()
        {
            this.TasksIBanks = new HashSet<TasksIBanks>();
        }
    
        public int ID { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompletionTime { get; set; }
        public int DisciplineID { get; set; }
        public int Author { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksIBanks> TasksIBanks { get; set; }
    }
}
